name: release
on:
  push:
    branches:
      - 'master'
      - 'beta'
      - 'alpha'
      - 'canary-*'
  pull_request: {}

# Cancel any previous run (see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn install --frozen-lockfile

  test:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.2-jammy
    steps:
      - run: yarn test

  storybook:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - run: yarn build-storybook

  release:
    needs: [test, storybook]
    runs-on: ubuntu-latest
    steps:
      # semantic-release skips not configured branches(see: release.config.js) or pull-requests
      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
